### ISSUE TITLE
Create Basic Documentation

### ISSUE THREAD

**Issue by senderle** [joelslee/textbook#3]
This is a prerequisite for #2, and it's something we should do now, for ourselves. This doesn't have to be perfectly comprehensible to outsiders, but it should cover any details that we might forget after a month.

**Comment by senderle** [comment]
Not assigning this to anyone yet because we probably have to deal with the other priority-high issues first.

**Comment by joelsjlee** [comment]
Updated very basic stuff to the README.md, mainly the absolute bare bones to be able to run the program. Probably will add more in the future. On my branch

**Comment by senderle** [comment]
I'm closing this under the assumption that what we have is good enough and anything more falls under the "excellent documentation" issue.
