### ISSUE TITLE
the text_to_md and voyant_gen services should work similarly

### ISSUE THREAD

**Issue by senderle** [joelslee/textbook#9]
Right now, the `text_to_md` service is based on a generic Python docker image, and all the configuration of that image happens inside `docker-compose.yml`. That's great! 

The `voyant_gen` service is based on an image we build from scratch, and the python script is hidden inside the `compose` folder, under `voyant_generator/bin`. That's what I told you to do, @joelslee, but I was wrong! This should work the same way as `text_to_md`.

It should be really easy to update `voyant_gen` to behave exactly like `text_to_md`. In addition to removing an unnecessary build step, this will ensure that all our scripts operate the same way, making maintenance easier. 

For now, create a new folder like `text_to_md`, but called `voyant_gen`, and put the python script in there. Then make the `voyant_gen` service look like `text_to_md`, making whatever tweaks are necessary. The upshot is that the one line command in `voyant_generator/bin/voyant_gen_script.sh` should probably just appear in `docker-compose.yml` as the `command` under the `voyant_gen` service.

**Comment by joelsjlee** [comment]
So I seemed to have made these changes as well. I deleted the `voyant_generation` folder under compose and moved over what was done in the Dockerfile and the shell script file to be in `docker-compose.yml`. I also created a folder in the root dir as requests above, and put my .py script there. Now the service in `docker-compose.yml` looks like this:

```
voyant_gen:
    image: python:3
    volumes:
      - ./corpora:/corpora
      - ./context:/input
      - ./voyant_gen:/workdir
    command: python -u workdir/voyant_gen.py /input/keywords.txt /input/corpus/ /corpora/
``` 

Now, I tried this with a clean project and while the server was running I inputted The Jungle. When I clicked on the link, I got some errors about the contents in `/static_pages/assets/` and I got an unformatted jekyll page. It had the text, but no formatting. It seemed like this was an error not unlike the one in #8 

Unfortunately (or fortunately (?)) I wasn't able to recreate the error message and didn't screen capture it. I am no longer running into the error, and I have tried the clean slate inputting The Jungle twice now with no errors. Hopefully this is just a one off I guess.
